service: desafioServerless

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dynamodb-local

custom:
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true
     


provider:
  name: aws

functions:
  createUser:
    handler: src/functions/createUser.handle
    events:
      - http:
          path: /todos/{id}
          method: POST
          cors: true
  listUser:
    handler: src/functions/listUser.handle
    events:
      - http:
          path: /todos/{id}
          method: GET
          cors: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
